version: '3'
services:
  database_icat:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=icat
      - MYSQL_DATABASE=icat
      - MYSQL_USER=icatdb
      - MYSQL_PASSWORD=icatbd
    volumes:
      - /var/lib/mysql
    restart: always

  database_topcat:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=icat
      - MYSQL_DATABASE=topcat
      - MYSQL_USER=icatdb
      - MYSQL_PASSWORD=icatbd
    volumes:
      - /var/lib/mysql
    restart: always

  webserver:
    build:
      context: .
    ports:
    - "8080:8080"
    - "4848:4848"
    volumes:
      - ${PWD}/apps/:/opt/payara41/etc/icat/
      - ${PWD}/mysql_connector/mysql-connector-java-5.1.48-bin.jar:/opt/payara41/glassfish/lib/mysql-connector-java-5.1.48-bin.jar
    depends_on:
    - database_icat
    - database_topcat
    restart: always


